using Polymorphismus.Classes;

Console.WriteLine("Зверинец");

Aviary withoutPredatorsAviary = new Aviary("Вольер без хищников", "в Саванне", 400, 0, 0, "Сено", "Фрукты", false);
ElephantAnimal elephant = new ElephantAnimal("Матильда", 15, 20, 100);
ElephantAnimal elephant2 = new ElephantAnimal("Матильда2", 15, 20, 100);
//elephant.Is();
//elephant.LivesIn();
//elephant.DoIt();
//elephant.EatingPortionOfFeed("Сено", 5, withoutPredatorsAviary);
//elephant.MakeASound();
//elephant.EatingPortionOfFeed("Торт", 5, withoutPredatorsAviary);
//elephant.CheckPredator("Сено");
//elephant.EatingPortionOfFeed("Сено", 5, withoutPredatorsAviary);
//elephant.Playing();
//elephant.PlayingWithRelatives();
//elephant.EatingPortionOfFeed("Сено", 5, withoutPredatorsAviary);
//Console.WriteLine();

Aviary penguinAviary = new Aviary("Пингвиний вольер", "на Льдине", 100, 0, 0, "Рыба", "Фрукты", true);
PenguinAnimal penguin = new PenguinAnimal("Петя", 3, 5, 10);
PenguinAnimal penguin2 = new PenguinAnimal("Петя2", 3, 5, 10);
//penguin.Is();
//penguin.LivesIn();
//penguin.DoIt();
//penguin.EatingPortionOfFeed("Рыба", 1, penguinAviary);
//penguin.MakeASound();
//penguin.EatingPortionOfFeed("Хлеб", 1, penguinAviary);
//penguin.CheckPredator("Рыба");
//penguin.EatingPortionOfFeed("Рыба", 1, penguinAviary);
//penguin.Playing();
//penguin.PlayingWithRelatives();
//penguin.EatingPortionOfFeed("Рыба", 1, penguinAviary);
//Console.WriteLine();

Aviary tigerAviary = new Aviary("Тигриный вольер", "в Джунглях", 300, 0, 0, "Мясо", "Фрукты", true);
TigerAnimal tiger = new TigerAnimal("Симба", 15, 10, 50);
TigerAnimal tiger2 = new TigerAnimal("Симба2", 15, 10, 50);
//tiger.Is();
//tiger.LivesIn();
//tiger.DoIt();
//tiger.EatingPortionOfFeed("Мясо", 5, tigerAviary);
//tiger.MakeASound();
//tiger.EatingPortionOfFeed("Трава", 5, tigerAviary);
//tiger.CheckPredator("Мясо");
//tiger.EatingPortionOfFeed("Мясо", 5, tigerAviary);
//tiger.Playing();
//tiger.PlayingWithRelatives();
//tiger.EatingPortionOfFeed("Мясо", 5, tigerAviary);
//Console.WriteLine();

Aviary frogAviary = new Aviary("Лягушачий вольер", "в Болоте", 25, 0, 0, "Насекомые", "Фрукты", true);
FrogAnimal frog = new FrogAnimal("Кваша", 6, 3, 5);
FrogAnimal frog2 = new FrogAnimal("Кваша2", 6, 3, 5);
//frog.Is();
//frog.LivesIn();
//frog.DoIt();
//frog.EatingPortionOfFeed("Насекомые", 2, frogAviary);
//frog.MakeASound();
//frog.EatingPortionOfFeed("Сыр", 2, frogAviary);
//frog.CheckPredator("Насекомые");
//frog.EatingPortionOfFeed("Насекомые", 2, frogAviary);
//frog.Playing();
//frog.PlayingWithRelatives();
//frog.EatingPortionOfFeed("Насекомые", 2, frogAviary);
//Console.WriteLine();

Aviary fishAviary = new Aviary("Аквариум", "в Океане", 100, 0, 0, "Планктон", "Фрукты", true);
FishAnimal fish = new FishAnimal("Нимо", 3, 1, 1);
FishAnimal fish2 = new FishAnimal("Нимо2", 3, 1, 1);
//fish.Is();
//fish.LivesIn();
//fish.DoIt();
//fish.EatingPortionOfFeed("Планктон", 1, fishAviary);
//fish.MakeASound();
//fish.EatingPortionOfFeed("Сахар", 1, fishAviary);
//fish.CheckPredator("Планктон");
//fish.EatingPortionOfFeed("Планктон", 1, fishAviary);
//fish.Playing();
//fish.PlayingWithRelatives();
//fish.EatingPortionOfFeed("Планктон", 1, fishAviary);
//Console.WriteLine();

OrangutanAnimal orangutan = new OrangutanAnimal("Губач", 9, 15, 25);
OrangutanAnimal orangutan2 = new OrangutanAnimal("Губач2", 9, 15, 25);
//orangutan.Is();
//orangutan.LivesIn();
//orangutan.DoIt();
//orangutan.EatingPortionOfFeed("Фрукты", 3, withoutPredatorsAviary);
//orangutan.MakeASound();
//orangutan.EatingPortionOfFeed("Чипсы", 3, withoutPredatorsAviary);
//orangutan.CheckPredator("Фрукты");
//orangutan.EatingPortionOfFeed("Фрукты", 3, withoutPredatorsAviary);
//orangutan.Playing();
//orangutan.PlayingWithRelatives();
//orangutan.EatingPortionOfFeed("Фрукты", 3, withoutPredatorsAviary);
//Console.WriteLine();

Console.WriteLine();
Console.WriteLine($"'Вольер без хищников'");
withoutPredatorsAviary.AddAnimal(elephant);
withoutPredatorsAviary.AddAnimal(elephant2);
withoutPredatorsAviary.AddAnimal(orangutan);
withoutPredatorsAviary.AddAnimal(orangutan2);
withoutPredatorsAviary.AddFeedInFeeder(30);
withoutPredatorsAviary.AddFeedInOtherFeeder(18);
withoutPredatorsAviary.MakeASoundAllAnimals();
withoutPredatorsAviary.FeedAllAnimals();
withoutPredatorsAviary.ShowRemainderFeeder();
withoutPredatorsAviary.ShowRemainderFeederOther();
withoutPredatorsAviary.SatietyCheckOfAllAnimals();
//withoutPredatorsAviary.ShowListAnimals();
withoutPredatorsAviary.RemoveAnimal("Матильда");
Console.WriteLine();

Console.WriteLine();
Console.WriteLine($"'Пингвиний вольер'");
penguinAviary.AddAnimal(penguin);
penguinAviary.AddAnimal(penguin2);
penguinAviary.AddFeedInFeeder(6);
penguinAviary.MakeASoundAllAnimals();
penguinAviary.FeedAllAnimals();
penguinAviary.ShowRemainderFeeder();
//penguinAviary.ShowListAnimals();
penguinAviary.RemoveAnimal("Петя");
Console.WriteLine();

Console.WriteLine();
Console.WriteLine($"'Тигриный вольер'");
tigerAviary.AddAnimal(tiger);
tigerAviary.AddAnimal(tiger2);
tigerAviary.AddFeedInFeeder(30);
tigerAviary.MakeASoundAllAnimals();
tigerAviary.FeedAllAnimals();
tigerAviary.ShowRemainderFeeder();
//tigerAviary.ShowListAnimals();
tigerAviary.RemoveAnimal("Симба");
Console.WriteLine();

Console.WriteLine();
Console.WriteLine($"'Лягушачий вольер'");
frogAviary.AddAnimal(frog);
frogAviary.AddAnimal(frog2);
frogAviary.AddFeedInFeeder(12);
frogAviary.MakeASoundAllAnimals();
frogAviary.FeedAllAnimals();
frogAviary.ShowRemainderFeeder();
//frogAviary.ShowListAnimals();
frogAviary.RemoveAnimal("Кваша");
Console.WriteLine();

Console.WriteLine();
Console.WriteLine($"'Аквариум'");
fishAviary.AddAnimal(fish);
fishAviary.AddAnimal(fish2);
fishAviary.AddFeedInFeeder(6);
fishAviary.MakeASoundAllAnimals();
fishAviary.FeedAllAnimals();
fishAviary.ShowRemainderFeeder();
//fishAviary.ShowListAnimals();
fishAviary.RemoveAnimal("Нимо");
Console.WriteLine();

Console.ReadLine();